# Generated by Django 3.2.7 on 2021-10-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_backend', to='blog_backend.writer'),
        ),
        migrations.AlterField(
            model_name='category',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='blog_backend', to='blog_backend.Article'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='article', to='blog_backend.Article'),
        ),
    ]
