# Generated by Django 3.2.7 on 2021-10-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0002_auto_20211010_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='blog_backend.writer'),
        ),
        migrations.AlterField(
            model_name='category',
            name='article',
            field=models.ManyToManyField(blank=True, to='blog_backend.Article'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='article',
            field=models.ManyToManyField(blank=True, to='blog_backend.Article'),
        ),
    ]
