# Generated by Django 3.2.7 on 2022-03-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0003_auto_20211010_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='img/blog'),
        ),
    ]
