version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/www/project
hooks:
  BeforeInstall:
    - location: scripts/stop_app.sh
      timeout: 6000
      runas: ubuntu
  AfterInstall:
    - location: scripts/stop_app.sh
      timeout: 6000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/stop_app.sh
      timeout: 6000
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 6000
      runas: ubuntu
