version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/code_deploy
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 6000
      runas: ubuntu
  AfterInstall:
    - location: scripts/migrate.sh
      timeout: 6000
      runas: ubuntu
