# Generated by Django 3.2.7 on 2022-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
