# Generated by Django 3.2.7 on 2021-10-19 06:18

from django.db import migrations
import upload_cv.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=upload_cv.formatChecker.ContentTypeRestrictedFileField(upload_to=''),
        ),
    ]
