# Generated by Django 3.2.7 on 2021-10-19 06:24

from django.db import migrations, models
import upload_cv.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_cv', '0002_alter_myfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='', validators=[upload_cv.models.file_size]),
        ),
    ]
