# Generated by Django 3.2.5 on 2021-09-21 04:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('category', models.IntegerField(choices=[(1, 'news'), (2, 'food'), (3, 'nature'), (4, 'story'), (5, 'tech')])),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
    ]
