# Generated by Django 3.2.7 on 2021-10-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='article',
            field=models.ManyToManyField(blank=True, null=True, related_name='backend', to='backend.Article'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='article',
            field=models.ManyToManyField(blank=True, null=True, related_name='article', to='backend.Article'),
        ),
    ]
