# Generated by Django 3.2.7 on 2021-10-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorest', '0003_auto_20211010_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfile',
            name='description',
        ),
    ]
