# Generated by Django 3.2.7 on 2021-10-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorest', '0005_alter_myfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
