# Generated by Django 3.2.7 on 2021-10-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorest', '0006_alter_myfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
