# Generated by Django 3.2.5 on 2021-09-12 10:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='answere',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
