# Generated by Django 3.2.5 on 2021-08-25 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0002_mychoice_pelatihan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myChoice',
        ),
    ]
