# Generated by Django 3.2.7 on 2021-11-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0003_alter_pelatihan_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelatihan',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')]),
        ),
    ]
