# Generated by Django 3.2.5 on 2021-08-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0003_delete_mychoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelatihan',
            name='no_hp',
        ),
        migrations.AddField(
            model_name='pelatihan',
            name='hp',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelatihan',
            name='jenis_kelamin',
            field=models.CharField(choices=[('p', 'Pria'), ('w', 'Wanita')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelatihan',
            name='jurusan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pelatihan',
            name='pendidikan',
            field=models.CharField(max_length=20),
        ),
    ]
