# Generated by Django 3.2.5 on 2021-08-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0004_auto_20210825_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='pesan',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='jurusan',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='pendidikan',
            new_name='study',
        ),
    ]
