# Generated by Django 3.2.5 on 2021-08-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0005_auto_20210825_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihan',
            old_name='jenis_kelamin',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='alasan',
            new_name='reason',
        ),
    ]
