# Generated by Django 3.2.5 on 2021-08-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0006_auto_20210825_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihan',
            old_name='reason',
            new_name='alasan',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='gender',
            new_name='jenis_kelamin',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='department',
            new_name='jurusan',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='study',
            new_name='pendidikan',
        ),
    ]
