# Generated by Django 3.2.5 on 2021-08-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0007_auto_20210825_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihan',
            old_name='jurusan',
            new_name='departemen',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='jenis_kelamin',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='alasan',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='pendidikan',
            new_name='study',
        ),
    ]
