# Generated by Django 3.2.5 on 2021-08-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0008_auto_20210825_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihan',
            old_name='departemen',
            new_name='jurusan',
        ),
    ]
