# Generated by Django 3.2.5 on 2021-08-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0009_rename_departemen_pelatihan_jurusan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihan',
            old_name='reason',
            new_name='alasan',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='gender',
            new_name='jenis_kelamin',
        ),
        migrations.RenameField(
            model_name='pelatihan',
            old_name='study',
            new_name='pendidikan',
        ),
    ]
