# Generated by Django 3.2.5 on 2021-08-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0011_auto_20210825_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihan',
            old_name='namae',
            new_name='name',
        ),
        migrations.AddField(
            model_name='pelatihan',
            name='departement',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
