# Generated by Django 3.2.5 on 2021-08-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0013_rename_name_pelatihan_nama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelatihan',
            old_name='departement',
            new_name='jurusan',
        ),
    ]
