# Generated by Django 3.2.5 on 2021-08-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0014_rename_departement_pelatihan_jurusan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelatihan',
            name='gender',
        ),
        migrations.AddField(
            model_name='pelatihan',
            name='yesorno',
            field=models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=1, verbose_name='Label...'),
        ),
    ]
