# Generated by Django 3.2.5 on 2021-08-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0015_auto_20210825_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelatihan',
            name='yesorno',
        ),
        migrations.AddField(
            model_name='pelatihan',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')], default=1),
        ),
    ]
