# Generated by Django 3.2.5 on 2021-08-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0016_auto_20210825_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelatihan',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')]),
        ),
    ]
