# Generated by Django 3.2.5 on 2021-08-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0017_alter_pelatihan_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term_Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=255)),
                ('Answere', models.CharField(max_length=255)),
            ],
        ),
    ]
