# Generated by Django 3.2.5 on 2021-08-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0018_term_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term_conditions',
            old_name='Answere',
            new_name='answere',
        ),
        migrations.RenameField(
            model_name='term_conditions',
            old_name='Question',
            new_name='question',
        ),
    ]
