# Generated by Django 3.2.5 on 2021-08-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0019_auto_20210830_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Term_Conditions',
            new_name='QA',
        ),
    ]
