# Generated by Django 3.2.5 on 2021-09-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0021_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=255)),
                ('a', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TermConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=255)),
            ],
        ),
    ]
