# Generated by Django 3.2.5 on 2021-09-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0022_privacypolicy_termconditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termconditions',
            old_name='a',
            new_name='description',
        ),
        migrations.AddField(
            model_name='termconditions',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
