# Generated by Django 3.2.5 on 2021-09-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0023_auto_20210910_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termconditions',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
