# Generated by Django 3.2.5 on 2021-09-10 04:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0024_alter_termconditions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termconditions',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
