# Generated by Django 3.2.5 on 2021-09-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revamp', '0025_alter_termconditions_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
